name: issue and PR lifecycle

on:
  issues:
    types: [opened, labeled, closed]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  schedule:
    - cron: '0 9 * * *'

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  lifecycle:
    uses: projectbluefin/common/.github/workflows/lifecycle.yml@233102e81ce425839dc5dcf00f830f14b9631d71
    with:
      brand_name: "Bluefin LTS"
    secrets: inherit
